"""Domain enumerations.

Note what these are NOT: they are not Postgres `ENUM` types. The columns that
use them are plain `String` with a CHECK constraint listing the valid values.

Why avoid native Postgres enums, despite them sounding like the "proper" choice:

* `ALTER TYPE ... ADD VALUE` cannot run inside a transaction block in older
  Postgres, which fights Alembic's transactional migrations.
* You **cannot remove** a value from a Postgres enum at all. Ever. The only
  route is create-new-type / migrate-columns / drop-old-type.
* Reordering values (they have an ordinal used by ORDER BY) is equally painful.

A CHECK constraint gets you the same guarantee — the database rejects invalid
values — while being a one-line migration to change. Meanwhile `StrEnum` gives
the Python side real type safety and autocomplete, and Pydantic will reject bad
values at the API boundary before they ever reach SQL.

That's three layers of validation (Pydantic, CHECK, StrEnum) with the flexible
one in the database. A good trade to be able to articulate.
"""

from enum import StrEnum


class ItemCondition(StrEnum):
    """Physical condition of a lot. Drives resale value expectations."""

    NEW = "new"  # deadstock / brand new with tags
    LIKE_NEW = "like_new"
    USED = "used"
    DAMAGED = "damaged"


class ListingStatus(StrEnum):
    """Lifecycle of a single listing on a single marketplace.

    Unlike an item lot, one listing genuinely has exactly one state at a time,
    which is why this one *is* stored as a column.
    """

    ACTIVE = "active"  # live and buyable
    SOLD = "sold"  # ended because it sold
    ENDED = "ended"  # delisted, expired, or cancelled without selling


class StockStatus(StrEnum):
    """Derived (never stored) status of an item lot.

    Computed from quantity vs. quantity_remaining. See the `stock_status`
    hybrid property on Item for why this is derived rather than a column.
    """

    IN_STOCK = "in_stock"  # nothing sold yet
    PARTIALLY_SOLD = "partially_sold"  # some units gone, some remain
    SOLD_OUT = "sold_out"  # every unit sold


class ProductCategory(StrEnum):
    """Broad catalog category, used for dashboard grouping."""

    SNEAKERS = "sneakers"
    STREETWEAR = "streetwear"
    COLLECTIBLE = "collectible"
    ACCESSORY = "accessory"
    OTHER = "other"


def sql_values(enum_cls: type[StrEnum]) -> str:
    """Render an enum as a SQL value list for a CHECK constraint.

    Returns e.g. ``'new','like_new','used','damaged'``.

    This keeps the constraint and the Python enum in sync automatically — add a
    member to ItemCondition and the next autogenerated migration picks it up,
    rather than the two drifting apart because someone edited one and not the
    other. Small helper, prevents a genuinely annoying class of bug.
    """
    return ",".join(f"'{member.value}'" for member in enum_cls)
