"""add full text search to items

Revision ID: 68cfee16db6e
Revises: f3fc4aebd31d
Create Date: 2026-09-08 22:59:34.504081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68cfee16db6e'
down_revision: Union[str, Sequence[str], None] = 'f3fc4aebd31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate does not detect extensions. Without this the gin_trgm_ops
    # index below fails with "operator class does not exist".
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.add_column('items', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(name, '')), 'A') || setweight(to_tsvector('english', coalesce(source, '')), 'B') || setweight(to_tsvector('english', coalesce(size, '')), 'C')", persisted=True), nullable=True))
    op.create_index('ix_items_name_trgm', 'items', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index('ix_items_search_vector', 'items', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    pg_trgm is deliberately left installed: extensions are database-wide and
    dropping one this migration did not exclusively own would break others.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_search_vector', table_name='items', postgresql_using='gin')
    op.drop_index('ix_items_name_trgm', table_name='items', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_column('items', 'search_vector')
    # ### end Alembic commands ###
