"""add search outbox

Revision ID: dc249f43729a
Revises: 68cfee16db6e
Create Date: 2026-09-08 23:18:40.574426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc249f43729a'
down_revision: Union[str, Sequence[str], None] = '68cfee16db6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_outbox',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('op', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("op IN ('index','delete')", name=op.f('ck_search_outbox_op_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_outbox'))
    )
    op.create_index('ix_search_outbox_pending', 'search_outbox', ['created_at'], unique=False, postgresql_where=sa.text('processed_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_outbox_pending', table_name='search_outbox', postgresql_where=sa.text('processed_at IS NULL'))
    op.drop_table('search_outbox')
    # ### end Alembic commands ###
