"""initial schema

Revision ID: f3fc4aebd31d
Revises: 
Create Date: 2026-09-07 17:31:47.392001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3fc4aebd31d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('default_fee_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_fee_pct IS NULL OR (default_fee_pct >= 0 AND default_fee_pct < 1)', name=op.f('ck_marketplaces_fee_pct_fraction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplaces')),
    sa.UniqueConstraint('slug', name=op.f('uq_marketplaces_slug'))
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=32), server_default=sa.text("'other'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('sneakers','streetwear','collectible','accessory','other')", name=op.f('ck_products_category_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('sku', 'size', name=op.f('uq_products_sku_size'), postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_products_brand_name', 'products', ['brand', 'name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_lower_email', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('condition', sa.String(length=20), server_default=sa.text("'new'"), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_remaining', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('acquisition_fee_total', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('purchased_at', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("condition IN ('new','like_new','used','damaged')", name=op.f('ck_items_condition_valid')),
    sa.CheckConstraint('acquisition_fee_total >= 0', name=op.f('ck_items_acq_fee_nonneg')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_items_quantity_positive')),
    sa.CheckConstraint('quantity_remaining <= quantity', name=op.f('ck_items_remaining_le_quantity')),
    sa.CheckConstraint('quantity_remaining >= 0', name=op.f('ck_items_remaining_nonneg')),
    sa.CheckConstraint('unit_cost >= 0', name=op.f('ck_items_unit_cost_nonneg')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('id', 'user_id', name=op.f('uq_items_id_user_id'))
    )
    op.create_index(op.f('ix_items_product_id'), 'items', ['product_id'], unique=False)
    op.create_index(op.f('ix_items_user_id'), 'items', ['user_id'], unique=False)
    op.create_index('ix_items_user_id_purchased_at', 'items', ['user_id', 'purchased_at'], unique=False)
    op.create_index('ix_items_user_in_stock', 'items', ['user_id'], unique=False, postgresql_where=sa.text('quantity_remaining > 0'))
    op.create_table('price_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('lowest_ask', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('highest_bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_sale', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sales_volume_72h', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.CheckConstraint('lowest_ask IS NOT NULL OR highest_bid IS NOT NULL OR last_sale IS NOT NULL', name=op.f('ck_price_snapshots_at_least_one_price')),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_price_snapshots_marketplace_id_marketplaces')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_price_snapshots_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_snapshots')),
    sa.UniqueConstraint('product_id', 'marketplace_id', 'captured_at', name=op.f('uq_price_snapshots_product_id_marketplace_id_captured_at'))
    )
    op.create_index(op.f('ix_price_snapshots_marketplace_id'), 'price_snapshots', ['marketplace_id'], unique=False)
    op.create_index('ix_price_snapshots_product_marketplace_captured', 'price_snapshots', ['product_id', 'marketplace_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('asking_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_listing_id', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'active') = (ended_at IS NULL)", name=op.f('ck_listings_ended_at_consistent')),
    sa.CheckConstraint("status IN ('active','sold','ended')", name=op.f('ck_listings_status_valid')),
    sa.CheckConstraint('asking_price >= 0', name=op.f('ck_listings_asking_price_nonneg')),
    sa.ForeignKeyConstraint(['item_id', 'user_id'], ['items.id', 'items.user_id'], name=op.f('fk_listings_item_id_user_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_listings_marketplace_id_marketplaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings')),
    sa.UniqueConstraint('id', 'item_id', name=op.f('uq_listings_id_item_id'))
    )
    op.create_index('ix_listings_item_id', 'listings', ['item_id'], unique=False)
    op.create_index(op.f('ix_listings_marketplace_id'), 'listings', ['marketplace_id'], unique=False)
    op.create_index('ix_listings_user_id_status', 'listings', ['user_id', 'status'], unique=False)
    op.create_index('uq_listings_active_item_marketplace', 'listings', ['item_id', 'marketplace_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('other_fees', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('unit_cost_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('acq_fee_allocated', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_order_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('platform_fee >= 0', name=op.f('ck_sales_platform_fee_nonneg')),
    sa.CheckConstraint('quantity_sold > 0', name=op.f('ck_sales_quantity_sold_positive')),
    sa.CheckConstraint('shipping_cost >= 0', name=op.f('ck_sales_shipping_cost_nonneg')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_sales_unit_price_nonneg')),
    sa.ForeignKeyConstraint(['item_id', 'user_id'], ['items.id', 'items.user_id'], name=op.f('fk_sales_item_id_user_id_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id', 'item_id'], ['listings.id', 'listings.item_id'], name=op.f('fk_sales_listing_id_item_id_listings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_sales_marketplace_id_marketplaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales')),
    sa.UniqueConstraint('marketplace_id', 'external_order_id', name=op.f('uq_sales_marketplace_id_external_order_id'))
    )
    op.create_index('ix_sales_item_id_user_id', 'sales', ['item_id', 'user_id'], unique=False)
    op.create_index('ix_sales_listing_id', 'sales', ['listing_id'], unique=False)
    op.create_index(op.f('ix_sales_marketplace_id'), 'sales', ['marketplace_id'], unique=False)
    op.create_index('ix_sales_user_id_sold_at', 'sales', ['user_id', 'sold_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_user_id_sold_at', table_name='sales')
    op.drop_index(op.f('ix_sales_marketplace_id'), table_name='sales')
    op.drop_index('ix_sales_listing_id', table_name='sales')
    op.drop_index('ix_sales_item_id_user_id', table_name='sales')
    op.drop_table('sales')
    op.drop_index('uq_listings_active_item_marketplace', table_name='listings', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_listings_user_id_status', table_name='listings')
    op.drop_index(op.f('ix_listings_marketplace_id'), table_name='listings')
    op.drop_index('ix_listings_item_id', table_name='listings')
    op.drop_table('listings')
    op.drop_index('ix_price_snapshots_product_marketplace_captured', table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_marketplace_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index('ix_items_user_in_stock', table_name='items', postgresql_where=sa.text('quantity_remaining > 0'))
    op.drop_index('ix_items_user_id_purchased_at', table_name='items')
    op.drop_index(op.f('ix_items_user_id'), table_name='items')
    op.drop_index(op.f('ix_items_product_id'), table_name='items')
    op.drop_table('items')
    op.drop_index('uq_users_lower_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_products_brand_name', table_name='products')
    op.drop_table('products')
    op.drop_table('marketplaces')
    # ### end Alembic commands ###
